# Generated by Django 4.2.16 on 2026-04-29 05:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('product_type', models.CharField(choices=[('saas', 'SaaS Application'), ('ai_tool', 'AI Tool'), ('digital_service', 'Digital Service'), ('bundle', 'Bundle'), ('course', 'Online Course'), ('template', 'Template / Asset'), ('api_access', 'API Access')], db_index=True, default='saas', max_length=20)),
                ('pricing_model', models.CharField(choices=[('one_time', 'One-Time Purchase'), ('monthly', 'Monthly Subscription'), ('yearly', 'Yearly Subscription'), ('pay_per_use', 'Pay Per Use'), ('free', 'Free')], db_index=True, default='monthly', max_length=12)),
                ('price_bdt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price in BDT', max_digits=10)),
                ('price_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price in platform credits', max_digits=12)),
                ('max_users', models.PositiveSmallIntegerField(default=1, help_text='Max seats/accounts per subscription')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/%Y/%m/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='products/banners/%Y/%m/')),
                ('demo_url', models.URLField(blank=True, default='', max_length=512)),
                ('external_url', models.URLField(blank=True, default='', help_text='External product / signup URL', max_length=512)),
                ('purchase_count', models.PositiveBigIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Subscription',
                'verbose_name_plural': 'Product Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/%Y/%m/')),
                ('website_url', models.URLField(blank=True, default='', max_length=512)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='DCE commission percentage on each sale', max_digits=5)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaaSAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_username', models.CharField(blank=True, default='', max_length=256)),
                ('account_password_enc', models.TextField(blank=True, default='', help_text='Fernet-encrypted account password')),
                ('account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('login_url', models.URLField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_provisioned', models.BooleanField(db_index=True, default=False)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_accounts', to='marketplace.product')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_account', to='marketplace.productsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SaaS Account',
                'verbose_name_plural': 'SaaS Accounts',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('body', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=256)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='marketplace.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.vendor'),
        ),
        migrations.AddIndex(
            model_name='productsubscription',
            index=models.Index(fields=['user', 'status'], name='marketplace_user_id_0652ec_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubscription',
            index=models.Index(fields=['status', 'ends_at'], name='marketplace_status_b45d44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-published_at'], name='marketplace_status_47fac6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status'], name='marketplace_product_347771_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='marketplace_is_feat_677222_idx'),
        ),
    ]
