# Generated by Django 4.2.16 on 2026-04-29 05:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='streaming.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name or emoji for UI display', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=256)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('course', 'Course'), ('tutorial', 'Tutorial'), ('documentary', 'Documentary'), ('short', 'Short Film')], db_index=True, default='movie', max_length=20)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter Plan'), ('growth', 'Growth Plan'), ('pro', 'Pro Plan'), ('ppv', 'Pay-Per-View')], db_index=True, default='growth', help_text='Minimum subscription plan required to watch', max_length=10)),
                ('ppv_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Credits charged for pay-per-view access', max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/')),
                ('trailer_url', models.URLField(blank=True, default='', max_length=1024)),
                ('video_file_key', models.CharField(blank=True, default='', help_text='S3 object key for master video file', max_length=1024)),
                ('hls_manifest_key', models.CharField(blank=True, default='', help_text='S3 key for HLS master playlist (.m3u8)', max_length=1024)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total duration in seconds')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='Bengali', max_length=32)),
                ('country', models.CharField(default='Bangladesh', max_length=64)),
                ('rating', models.CharField(blank=True, default='', help_text='Content rating: G, PG, PG-13, R, etc.', max_length=10)),
                ('cast', models.JSONField(blank=True, default=list, help_text='List of cast member dicts: {name, role, image_url}')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Free-form searchable tags')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('max_concurrent_streams', models.PositiveSmallIntegerField(default=3, help_text='Max simultaneous streams per user for this content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='videos', to='streaming.category')),
                ('genres', models.ManyToManyField(blank=True, related_name='videos', to='streaming.genre')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_url_key', models.CharField(blank=True, default='', help_text='S3 key the signed URL was generated for', max_length=1024)),
                ('signed_url_expires_at', models.DateTimeField(blank=True, help_text='When the signed streaming URL expires', null=True)),
                ('quality', models.CharField(choices=[('360p', '360p SD'), ('480p', '480p SD'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4k', '4K Ultra HD')], default='720p', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('kicked', 'Kicked — concurrency limit')], db_index=True, default='active', max_length=10)),
                ('last_heartbeat_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('heartbeat_count', models.PositiveIntegerField(default=0)),
                ('ended_position_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Stream Session',
                'verbose_name_plural': 'Stream Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(limit_choices_to={'content_type': 'series'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['series', 'season_number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/%Y/%m/')),
                ('is_free_preview', models.BooleanField(default=False, help_text='Allow non-subscribers to watch this episode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='streaming.season')),
                ('video', models.OneToOneField(help_text='Video object containing the episode media', on_delete=django.db.models.deletion.PROTECT, related_name='episode_detail', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['season', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_seconds', models.PositiveIntegerField(default=0, help_text='Last watched position in seconds')),
                ('completed', models.BooleanField(default=False, help_text='True if user watched ≥ 90% of the content')),
                ('watch_count', models.PositiveIntegerField(default=1, help_text='Number of times fully watched')),
                ('last_watched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Watch History',
                'verbose_name_plural': 'Watch Histories',
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', '-last_watched_at'], name='streaming_w_user_id_d11903_idx'), models.Index(fields=['user', 'completed'], name='streaming_w_user_id_c802d6_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(help_text="e.g. 'Bengali', 'English'", max_length=32)),
                ('language_code', models.CharField(help_text="ISO 639-1 code, e.g. 'bn', 'en'", max_length=8)),
                ('subtitle_key', models.CharField(help_text='S3 key for .vtt or .srt subtitle file', max_length=1024)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Video Subtitle',
                'verbose_name_plural': 'Video Subtitles',
                'unique_together': {('video', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Video Rating',
                'verbose_name_plural': 'Video Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.CharField(choices=[('360p', '360p SD'), ('480p', '480p SD'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4k', '4K Ultra HD')], default='720p', max_length=10)),
                ('video_file_key', models.CharField(help_text='S3 key for this quality variant', max_length=1024)),
                ('hls_playlist_key', models.CharField(blank=True, default='', help_text='S3 key for HLS playlist for this quality level', max_length=1024)),
                ('bitrate_kbps', models.PositiveIntegerField(default=0, help_text='Video bitrate in kbps')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False, help_text='Set True once encoding is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_variants', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Video Quality Variant',
                'verbose_name_plural': 'Video Quality Variants',
                'ordering': ['video', 'quality'],
                'unique_together': {('video', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='VideoAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied — Insufficient Plan'), ('expired', 'Access Denied — Signed URL Expired'), ('fraud', 'Blocked — Fraud Detected')], db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='streaming.streamsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_access_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='streaming.video')),
            ],
            options={
                'verbose_name': 'Video Access Log',
                'verbose_name_plural': 'Video Access Logs',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='streaming_v_user_id_65e50c_idx'), models.Index(fields=['result', '-created_at'], name='streaming_v_result_3abbb8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', '-published_at'], name='streaming_v_status_9657b9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['content_type', 'status'], name='streaming_v_content_4ae63e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', 'status'], name='streaming_v_is_feat_f1002a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['access_level'], name='streaming_v_access__db8d41_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='streaming_v_slug_988bde_idx'),
        ),
        migrations.AddIndex(
            model_name='streamsession',
            index=models.Index(fields=['user', 'status'], name='streaming_s_user_id_c15254_idx'),
        ),
        migrations.AddIndex(
            model_name='streamsession',
            index=models.Index(fields=['user', 'video', 'status'], name='streaming_s_user_id_8eb60f_idx'),
        ),
        migrations.AddIndex(
            model_name='streamsession',
            index=models.Index(fields=['last_heartbeat_at', 'status'], name='streaming_s_last_he_9418ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
    ]
