# Generated by Django 4.2.16 on 2026-04-29 05:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_credits', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], db_index=True, max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('price_bdt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('price_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('max_concurrent_streams', models.PositiveSmallIntegerField(default=2, help_text='Max simultaneous streams for this plan')),
                ('max_devices', models.PositiveSmallIntegerField(default=3)),
                ('ai_credits_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly AI credits included in plan', max_digits=12)),
                ('access_level', models.CharField(default='starter', help_text='Maps to streaming AccessLevel: starter/growth/pro', max_length=10)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show as recommended/popular plan in UI')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price_bdt'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=128)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.bundle')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Bundle Item',
                'verbose_name_plural': 'Bundle Items',
                'unique_together': {('bundle', 'plan')},
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='bundles', through='subscriptions.BundleItem', to='subscriptions.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='active', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, help_text='Grace period end (set when status → grace)', null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('renewal_credits_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Credits deducted for last renewal', max_digits=12)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=256)),
                ('payment_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'), models.Index(fields=['status', 'ends_at'], name='subscriptio_status_4c9d7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=64)),
                ('feature_label', models.CharField(max_length=256)),
                ('feature_value', models.CharField(blank=True, default='', max_length=128)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Bold/highlight this feature in the UI')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['plan', 'sort_order'],
                'unique_together': {('plan', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='BundleSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='active', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.bundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bundle Subscription',
                'verbose_name_plural': 'Bundle Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_92f8d3_idx'), models.Index(fields=['status', 'ends_at'], name='subscriptio_status_a4920f_idx')],
            },
        ),
    ]
