# Generated by Django 4.2.16 on 2026-04-29 05:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Bangladesh mobile number in E.164 format, e.g. +8801712345678', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Bangladesh format: +880XXXXXXXXXX (e.g. +8801712345678)', regex='^\\+880[1-9]\\d{8}$')], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Optional — used for receipts and account recovery', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (JPEG/PNG, max 5 MB)', null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False, help_text='Becomes True after a successful OTP verification', verbose_name='phone verified')),
                ('is_active', models.BooleanField(default=True, help_text='Unset to soft-disable the account without deleting it', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Allows access to Django admin site', verbose_name='staff status')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='KYC status')),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC submitted at')),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC reviewed at')),
                ('kyc_rejection_reason', models.TextField(blank=True, verbose_name='KYC rejection reason')),
                ('referral_code', models.CharField(blank=True, db_index=True, help_text='Unique code this user can share to earn bonuses', max_length=16, unique=True, verbose_name='referral code')),
                ('referral_bonus_credited', models.BooleanField(default=False, help_text='True once the sign-up referral bonus has been paid out', verbose_name='referral bonus credited')),
                ('device_tokens', models.JSONField(blank=True, default=list, help_text='FCM / APNs push notification tokens; list of dicts', verbose_name='device tokens')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='last login IP')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='referred by')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, help_text='Unique hardware or browser fingerprint identifier', max_length=255, verbose_name='device ID')),
                ('device_type', models.CharField(choices=[('android', 'Android Mobile'), ('ios', 'iOS Mobile'), ('web', 'Web Browser'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='android', max_length=20, verbose_name='device type')),
                ('device_name', models.CharField(blank=True, help_text='Human-readable label, e.g. "Bashir\'s Galaxy S23"', max_length=100, verbose_name='device name')),
                ('push_token', models.TextField(blank=True, help_text='FCM registration token or APNs device token', verbose_name='push token')),
                ('app_version', models.CharField(blank=True, help_text='Semantic version of the client app, e.g. "2.3.1"', max_length=20, verbose_name='app version')),
                ('os_version', models.CharField(blank=True, max_length=40, verbose_name='OS version')),
                ('last_active', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='last active')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='last IP')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive devices will not receive push notifications', verbose_name='is active')),
                ('is_trusted', models.BooleanField(default=False, help_text='Trusted devices may bypass additional auth checks', verbose_name='is trusted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user device',
                'verbose_name_plural': 'user devices',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_device_user_active'), models.Index(fields=['push_token'], name='idx_device_push_token')],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(help_text='SHA-256 hex digest of the 6-digit OTP code', max_length=64, verbose_name='OTP hash')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('withdrawal', 'Withdrawal'), ('password_reset', 'Password Reset'), ('phone_change', 'Phone Change'), ('kyc', 'KYC Verification')], db_index=True, max_length=20, verbose_name='purpose')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='is used')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts', verbose_name='verification attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='requester IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OTP verification',
                'verbose_name_plural': 'OTP verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='idx_otp_user_purpose'), models.Index(fields=['expires_at'], name='idx_otp_expires')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='idx_user_phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referral_code'], name='idx_user_referral'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['kyc_status'], name='idx_user_kyc'),
        ),
    ]
