# Generated by Django 4.2.16 on 2026-04-29 05:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wallet ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current BDT balance available for use', max_digits=10, verbose_name='BDT Balance')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform credits balance (1 BDT = 10 credits by default)', max_digits=10, verbose_name='Credit Balance')),
                ('is_frozen', models.BooleanField(default=False, help_text='Frozen wallets cannot perform transactions', verbose_name='Is Frozen')),
                ('frozen_reason', models.TextField(blank=True, null=True, verbose_name='Frozen Reason')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Deposited (Lifetime BDT)')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Spent (Lifetime BDT equivalent)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Withdrawn (Lifetime BDT)')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10, verbose_name='Loyalty Tier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Transaction UUID')),
                ('transaction_id', models.CharField(help_text='Human-readable ID, format: TXN-YYYYMMDD-XXXXXXXX', max_length=30, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('AI_USAGE', 'AI Usage'), ('STREAMING', 'Streaming'), ('MARKETPLACE', 'Marketplace'), ('SUBSCRIPTION', 'Subscription'), ('REFUND', 'Refund'), ('BONUS', 'Bonus'), ('REFERRAL', 'Referral')], max_length=20, verbose_name='Transaction Type')),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz'), ('INTERNAL', 'Internal Transfer'), ('SYSTEM', 'System')], max_length=20, verbose_name='Payment Method')),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (BDT)')),
                ('amount_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount (Credits)')),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=8, verbose_name='BDT to Credits Conversion Rate')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=15, verbose_name='Status')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='External payment gateway reference', max_length=255, null=True, verbose_name='Gateway Transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw response payload from payment gateway', verbose_name='Gateway Response')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID')),
                ('service_reference', models.JSONField(blank=True, default=dict, help_text='JSON detailing which service and resource was consumed', verbose_name='Service Reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Ledger Entry ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6, verbose_name='Entry Type')),
                ('account_type', models.CharField(choices=[('USER_WALLET', 'User Wallet'), ('PLATFORM_REVENUE', 'Platform Revenue'), ('PROVIDER_COST', 'Provider Cost'), ('REFUND_RESERVE', 'Refund Reserve')], max_length=20, verbose_name='Account Type')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('CREDITS', 'Platform Credits'), ('USD', 'US Dollar')], default='BDT', max_length=10, verbose_name='Currency')),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Balance Before')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Balance After')),
                ('reference_id', models.UUIDField(db_index=True, help_text='Shared UUID linking paired debit/credit entries', verbose_name='Reference ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='wallet.transaction', verbose_name='Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Deposit Request ID')),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (BDT)')),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz')], max_length=15, verbose_name='Payment Method')),
                ('phone_number', models.CharField(blank=True, help_text='Required for bKash and Nagad payments', max_length=20, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=15, verbose_name='Status')),
                ('gateway_session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Session ID')),
                ('gateway_payment_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Gateway Payment URL')),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text='Webhook payload from payment gateway', verbose_name='Callback Data')),
                ('expires_at', models.DateTimeField(help_text='Deposit request expires 30 minutes after creation', verbose_name='Expires At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Withdrawal Request ID')),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (BDT)')),
                ('credits_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform credits deducted to cover withdrawal amount', max_digits=10, verbose_name='Credits Deducted')),
                ('withdrawal_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BANK', 'Bank Transfer')], max_length=10, verbose_name='Withdrawal Method')),
                ('account_number', models.CharField(help_text='Mobile number for bKash/Nagad, account number for bank transfer', max_length=50, verbose_name='Account Number / Phone')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Admin Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin user who approved or rejected this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_with_user_id_b5987e_idx'), models.Index(fields=['status'], name='wallet_with_status_f692e5_idx'), models.Index(fields=['withdrawal_method'], name='wallet_with_withdra_3b2511_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Audit Log ID')),
                ('action', models.CharField(choices=[('BALANCE_CHECK', 'Balance Check'), ('DEBIT_ATTEMPT', 'Debit Attempt'), ('CREDIT_APPLIED', 'Credit Applied'), ('FREEZE_APPLIED', 'Freeze Applied'), ('UNFREEZE', 'Unfreeze'), ('OVERDRAFT_PREVENTED', 'Overdraft Prevented')], max_length=30, verbose_name='Action')),
                ('old_balance', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Old Balance')),
                ('new_balance', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='New Balance')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Null indicates a system-automated action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Audit Log',
                'verbose_name_plural': 'Wallet Audit Logs',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__b920fd_idx'), models.Index(fields=['action'], name='wallet_wall_action_8c2da1_idx'), models.Index(fields=['performed_by'], name='wallet_wall_perform_8a339d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_wall_user_id_03e396_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['tier'], name='wallet_wall_tier_c21e07_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_frozen'], name='wallet_wall_is_froz_e9a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='wallet_tran_transac_12527c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_46afdf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__abbc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_a49b73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_7debff_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_transaction_id'], name='wallet_tran_gateway_2c6255_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_ledg_wallet__463b44_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference_id'], name='wallet_ledg_referen_65ba91_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account_type', 'entry_type'], name='wallet_ledg_account_1ac49c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction'], name='wallet_ledg_transac_a947a0_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['user', '-created_at'], name='wallet_depo_user_id_5c0902_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['status'], name='wallet_depo_status_5ce6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['gateway_session_id'], name='wallet_depo_gateway_3e2bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['expires_at'], name='wallet_depo_expires_54287e_idx'),
        ),
    ]
